Improve formatter workflow

diff --git a/.github/workflows/FormatCheck.yml b/.github/workflows/FormatCheck.yml
--- a/.github/workflows/FormatCheck.yml
+++ b/.github/workflows/FormatCheck.yml
@@ -8,56 +8,103 @@ on:
         default: "1"
         required: false
         type: string
-      runic-version:
-        description: "Version of Runic to use"
-        default: "1"
-        required: false
-        type: string
-      concurrent-jobs:
-        description: "Run jobs concurrently"
-        default: false
-        required: false
-        type: boolean
-      cancel-in-progress:
-        description: "Cancel jobs in-progress in favor of a new one in the same concurrency group"
-        default: true
-        required: false
-        type: boolean
-      format-suggestions:
-        description: "Post formatting changes as code suggestions"
-        default: true
-        required: false
-        type: boolean
 
 concurrency:
-  group: "${{ inputs.concurrent-jobs && github.run_id || github.ref  }}:${{ github.workflow }}"
-  cancel-in-progress: ${{ !inputs.concurrent-jobs && inputs.cancel-in-progress }}
+  group: "${{ github.run_id || github.ref  }}:${{ github.workflow }}"
+  cancel-in-progress: true
 
 jobs:
   format-check:
-    name: "Check Formatting"
+    name: "Runic"
     runs-on: ubuntu-latest
+
     permissions:
       contents: read
-      checks: write
-      issues: write
+      actions: write
       pull-requests: write
-    steps:
-      - uses: actions/checkout@v4
 
-      - uses: julia-actions/setup-julia@v2
+    steps:
+      - name: Check out repository
+        uses: actions/checkout@v5
         with:
-          version: "${{ inputs.julia-version }}"
+          ref: ${{github.event.pull_request.head.ref}}
+          repository: ${{github.event.pull_request.head.repo.full_name}}
+          fetch-depth: 0
+
+      - name: Add upstream remote
+        run: |
+          git remote add upstream https://github.com/${{ github.repository }}
+          git fetch upstream
+
+      - name: Setup Julia
+        uses: julia-actions/setup-julia@v2
+        with:
+          version: ${{ inputs.julia-version }}
+          arch: 'x64'
+
       - uses: julia-actions/cache@v2
 
-      - uses: fredrikekre/runic-action@v1
-        with:
-          version: "${{ inputs.runic-version }}"
-          format_files: ${{ inputs.format_suggestions }}
-        continue-on-error : ${{ github.event_name == 'pull_request' && inputs.format_suggestions }}
+      - name: Install Runic
+        run: |
+          julia --project=@runic -e 'using Pkg; Pkg.add("Runic")'
+          curl -o git-runic https://raw.githubusercontent.com/fredrikekre/Runic.jl/master/bin/git-runic
+          chmod +x git-runic
+          sudo mv git-runic /usr/local/bin
 
-      - uses: reviewdog/action-suggester@v1
-        if: ${{ github.event_name == 'pull_request' && inputs.format_suggestions }}
+      - name: Run Runic
+        id: runic
+        run: |
+          set +e
+          MERGE_BASE=$(git merge-base upstream/${{ github.base_ref }} HEAD) || exit 1
+          DIFF=$(git runic --diff $MERGE_BASE)
+          EXIT_CODE=$?
+
+          echo "exit_code=$EXIT_CODE" >> $GITHUB_OUTPUT
+          echo "diff<<EOF" >> $GITHUB_OUTPUT
+          echo "$DIFF" >> $GITHUB_OUTPUT
+          echo "EOF" >> $GITHUB_OUTPUT
+
+          # if Runic failed, bail out
+          [ $EXIT_CODE -eq 2 ] && exit 1 || exit 0
+
+      - name: Find comment
+        uses: peter-evans/find-comment@v3
+        id: find-comment
         with:
-          tool_name: Runic
-          fail_level: warning
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-author: 'github-actions[bot]'
+          body-includes: '<!-- runic-format-summary -->'
+
+      - name: Comment formatting suggestions
+        if: steps.runic.outputs.exit_code == 1
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          comment-id: ${{ steps.find-comment.outputs.comment-id }}
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            <!-- runic-format-summary -->
+
+            Your PR requires formatting changes to meet the project's style guidelines.
+            Please consider running [Runic](https://github.com/fredrikekre/Runic.jl) (`git runic ${{ github.base_ref }}`) to apply these changes.
+
+            <details>
+            <summary>Click here to view the suggested changes.</summary>
+
+            ~~~diff
+            ${{ steps.runic.outputs.diff }}
+            ~~~
+
+            </details>
+          edit-mode: replace
+
+      - name: Update stale comment
+        if: steps.runic.outputs.exit_code == 0 && steps.find-comment.outputs.comment-id
+        uses: peter-evans/create-or-update-comment@v4
+        with:
+          comment-id: ${{ steps.find-comment.outputs.comment-id }}
+          issue-number: ${{ github.event.pull_request.number }}
+          body: |
+            <!-- runic-format-summary -->
+
+            Your PR no longer requires formatting changes. Thank you for your contribution!
+          edit-mode: replace
